server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wishlist_bot
    username: wishlist_bot
    password: s3cr3t

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      format_sql: false
    show-sql: false


telegram:
  botUsername:
  botToken:
  webAppUrl: https://wishlist-bot.vercel.app

opengraph:
  apiKey:

cloudinary:
  url: